# This file was generated by GoReleaser. DO NOT EDIT.
class Ownershit < Formula
  desc "Manage the ownership of your repositories."
  homepage ""
  version "0.3.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/klauern/ownershit/releases/download/v0.3.2/ownershit_0.3.2_Darwin_x86_64.tar.gz"
    sha256 "42405005fd6f49131f412c208692a0f475334119a4093414b27bdd035b2172f2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/klauern/ownershit/releases/download/v0.3.2/ownershit_0.3.2_Linux_x86_64.tar.gz"
      sha256 "8cb25d6004d2018a402da4912f172020e5fc447275ed9f0c8dc58bc3c3417732"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
      else
        url "https://github.com/klauern/ownershit/releases/download/v0.3.2/ownershit_0.3.2_Linux_armv6.tar.gz"
        sha256 "2e55908b114fe394f1464fd6f151aab1055230633cd12f19d06b4102337833cd"
      end
    end
  end

  def install
    bin.install "ownershit"
  end
end
