before:
  hooks:
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  main: ./cmd/ownershit/main.go
  binary: ownershit
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  - arm
archives:
  - id: archive
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
  - repository:
      owner: klauern
      name: homebrew-ownershit
      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    description: "Manage the ownership of your repositories."
    homepage: "https://github.com/klauern/ownershit"
    license: "MIT"
    skip_upload: false
