# https://taskfile.dev

version: "2"

tasks:
  dev:
    desc: set up development environment
    env:
      GO111MODULE: on
    cmds:
      - go get ./...
      - go get github.com/golang/mock/mockgen@latest

  build:
    desc: Build locally
    cmds:
      - go build ./cmd/ownershit/main.go

  install:
    desc: install binary locally
    cmds:
      - go install ./cmd/ownershit/main.go

  fmt:
    desc: format
    cmds:
      - go fmt

  lint:
    desc: run GolangCI-Lint
    cmds:
    - golangci-lint run

  mocks:
    desc: generate the mocks for use with testing and stubbing
    cmds:
      - go generate

  run:
    desc: run off of source
    cmds:
      - go run *.go

  test:
    desc: run tests
    deps:
      - mocks
    cmds:
      - go test -race -coverprofile=coverage.out ./...
  test-cover:
    desc: run tests, and then show coverage output
    cmds:
      - task: test
      - cmd: go tool cover -html=coverage.out
