# https://taskfile.dev

version: "3"

tasks:
  dev:
    desc: set up development environment
    cmds:
      - go mod tidy
      - go install go.uber.org/mock/mockgen

  build:
    desc: Build locally
    cmds:
      - go build ./cmd/ownershit/main.go
      - go build ./cmd/genqlient
      - rm main genqlient

  install:
    desc: install binary locally
    cmds:
      - go install ./cmd/ownershit/main.go

  fmt:
    desc: format
    cmds:
      - go fmt
      - gofmt -w -s .

  lint:
    desc: run GolangCI-Lint
    cmds:
      - golangci-lint run

  mocks:
    desc: generate the mocks for use with testing and stubbing
    cmds:
      - go generate ./...

  test-query:
    desc: run a raw query with my name
    cmds:
      - go run ./cmd/ownershit/main.go archive query --username klauern
  test:
    desc: run tests
    deps:
      - mocks
    cmds:
      - go test -race -coverprofile=coverage.out ./...
  test-cover:
    desc: run tests, and then show coverage output
    cmds:
      - task: test
      - cmd: go tool cover -html=coverage.out

  gql:download-schema:
    desc: download GitHub's GraphQL schema
    cmds:
      - cmd: curl -o schema.graphql https://docs.github.com/public/fpt/schema.docs.graphql

  gql:generate-client:
    desc: create GraphQL generated client for GitHub v4
    cmds:
      - cmd: go run github.com/Khan/genqlient
