# https://taskfile.dev

version: "3"

tasks:
  dev:
    desc: set up development environment
    cmds:
      - go mod tidy
      - go install go.uber.org/mock/mockgen
      - go install golang.org/x/vuln/cmd/govulncheck@latest

  build:
    desc: Build locally
    cmds:
      - go build ./cmd/ownershit/main.go
      - go build ./cmd/genqlient
      - rm main genqlient

  install:
    desc: install binary locally
    cmds:
      - go install ./cmd/ownershit

  fmt:
    desc: format
    cmds:
      - go fmt
      - gofmt -w -s .

  lint:
    desc: run GolangCI-Lint
    cmds:
      - golangci-lint run

  mocks:
    desc: generate the mocks for use with testing and stubbing
    cmds:
      - go generate ./...

  test-query:
    desc: run a raw query with my name
    cmds:
      - go run ./cmd/ownershit/main.go archive query --username klauern
  test:
    desc: run tests
    deps:
      - mocks
    cmds:
      - go test -race -coverprofile=coverage.out ./...

  test-all:
    desc: run tests with security checks
    deps:
      - mocks
    cmds:
      - go test -race -coverprofile=coverage.out ./...
      - task: security
  test-cover:
    desc: run tests, and then show coverage output
    cmds:
      - task: test
      - cmd: go tool cover -html=coverage.out

  gql:download-schema:
    desc: download GitHub's GraphQL schema
    cmds:
      - cmd: curl -o schema.graphql https://docs.github.com/public/fpt/schema.docs.graphql

  gql:generate-client:
    desc: create GraphQL generated client for GitHub v4
    cmds:
      - cmd: go run github.com/Khan/genqlient

  security:
    desc: run security vulnerability check
    cmds:
      - govulncheck ./...

  release:
    desc: create a new release (requires VERSION=x.x.x)
    cmds:
      - cmd: |
          if [ -z "{{.VERSION}}" ]; then
            echo "❌ VERSION is required. Usage: task release VERSION=v0.6.0"
            exit 1
          fi
      - task: test-all
      - task: lint
      - cmd: |
          echo "🏷️  Creating release tag {{.VERSION}}"
          git tag {{.VERSION}}
          git push origin {{.VERSION}}
          echo "✅ Release {{.VERSION}} created! GoReleaser will build and publish automatically."
          echo "🔗 Check the release at: https://github.com/klauern/ownershit/releases/tag/{{.VERSION}}"
