// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Khan/genqlient/graphql (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination mocks/client_mocks.go github.com/Khan/genqlient/graphql Client
//

// Package mock_graphql is a generated GoMock package.
package mock_graphql

import (
	context "context"
	reflect "reflect"

	graphql "github.com/Khan/genqlient/graphql"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// MakeRequest mocks base method.
func (m *MockClient) MakeRequest(ctx context.Context, req *graphql.Request, resp *graphql.Response) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeRequest", ctx, req, resp)
	ret0, _ := ret[0].(error)
	return ret0
}

// MakeRequest indicates an expected call of MakeRequest.
func (mr *MockClientMockRecorder) MakeRequest(ctx, req, resp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeRequest", reflect.TypeOf((*MockClient)(nil).MakeRequest), ctx, req, resp)
}
