name: Go Testing, Linting, Etc.

on:
  push:

env:
  GO111MODULE: on
  # go test -race needs CGO set
  # CGO_ENABLED: 0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        id: go

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: "3.12.0"
      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Setup other Dependencies
        run: |
          task dev
          GO111MODULE=on go get github.com/golang/mock/mockgen@latest

      - name: Build
        run: task build

      - name: Test
        run: task test
